// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// EmailResponse defines model for EmailResponse.
type EmailResponse struct {
	Content        *string `json:"content,omitempty"`
	RecipientEmail *string `json:"recipientEmail,omitempty"`
	Status         *string `json:"status,omitempty"`
	Subject        *string `json:"subject,omitempty"`
}

// EmailVerificationRequest defines model for EmailVerificationRequest.
type EmailVerificationRequest struct {
	Code           *string `json:"code,omitempty"`
	Name           *string `json:"name,omitempty"`
	RecipientEmail *string `json:"recipientEmail,omitempty"`
}

// PasswordResetRequest defines model for PasswordResetRequest.
type PasswordResetRequest struct {
	AvatarUrl      *string `json:"avatarUrl,omitempty"`
	Code           *string `json:"code,omitempty"`
	FullName       *string `json:"fullName,omitempty"`
	RecipientEmail *string `json:"recipientEmail,omitempty"`
}

// PasswordResetResponse defines model for PasswordResetResponse.
type PasswordResetResponse struct {
	AvatarUrl      *string `json:"avatarUrl,omitempty"`
	Code           *string `json:"code,omitempty"`
	Content        *string `json:"content,omitempty"`
	FullName       *string `json:"fullName,omitempty"`
	RecipientEmail *string `json:"recipientEmail,omitempty"`
	Status         *string `json:"status,omitempty"`
	Subject        *string `json:"subject,omitempty"`
}

// SendEmailVerificationCodeJSONRequestBody defines body for SendEmailVerificationCode for application/json ContentType.
type SendEmailVerificationCodeJSONRequestBody = EmailVerificationRequest

// SendPasswordResetCodeJSONRequestBody defines body for SendPasswordResetCode for application/json ContentType.
type SendPasswordResetCodeJSONRequestBody = PasswordResetRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// SendEmailVerificationCodeWithBody request with any body
	SendEmailVerificationCodeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SendEmailVerificationCode(ctx context.Context, body SendEmailVerificationCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SendPasswordResetCodeWithBody request with any body
	SendPasswordResetCodeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SendPasswordResetCode(ctx context.Context, body SendPasswordResetCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) SendEmailVerificationCodeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendEmailVerificationCodeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendEmailVerificationCode(ctx context.Context, body SendEmailVerificationCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendEmailVerificationCodeRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendPasswordResetCodeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendPasswordResetCodeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendPasswordResetCode(ctx context.Context, body SendPasswordResetCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendPasswordResetCodeRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewSendEmailVerificationCodeRequest calls the generic SendEmailVerificationCode builder with application/json body
func NewSendEmailVerificationCodeRequest(server string, body SendEmailVerificationCodeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSendEmailVerificationCodeRequestWithBody(server, "application/json", bodyReader)
}

// NewSendEmailVerificationCodeRequestWithBody generates requests for SendEmailVerificationCode with any type of body
func NewSendEmailVerificationCodeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/email-verification")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSendPasswordResetCodeRequest calls the generic SendPasswordResetCode builder with application/json body
func NewSendPasswordResetCodeRequest(server string, body SendPasswordResetCodeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSendPasswordResetCodeRequestWithBody(server, "application/json", bodyReader)
}

// NewSendPasswordResetCodeRequestWithBody generates requests for SendPasswordResetCode with any type of body
func NewSendPasswordResetCodeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/password-reset")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// SendEmailVerificationCodeWithBodyWithResponse request with any body
	SendEmailVerificationCodeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendEmailVerificationCodeResponse, error)

	SendEmailVerificationCodeWithResponse(ctx context.Context, body SendEmailVerificationCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*SendEmailVerificationCodeResponse, error)

	// SendPasswordResetCodeWithBodyWithResponse request with any body
	SendPasswordResetCodeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendPasswordResetCodeResponse, error)

	SendPasswordResetCodeWithResponse(ctx context.Context, body SendPasswordResetCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*SendPasswordResetCodeResponse, error)
}

type SendEmailVerificationCodeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r SendEmailVerificationCodeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SendEmailVerificationCodeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SendPasswordResetCodeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r SendPasswordResetCodeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SendPasswordResetCodeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// SendEmailVerificationCodeWithBodyWithResponse request with arbitrary body returning *SendEmailVerificationCodeResponse
func (c *ClientWithResponses) SendEmailVerificationCodeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendEmailVerificationCodeResponse, error) {
	rsp, err := c.SendEmailVerificationCodeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendEmailVerificationCodeResponse(rsp)
}

func (c *ClientWithResponses) SendEmailVerificationCodeWithResponse(ctx context.Context, body SendEmailVerificationCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*SendEmailVerificationCodeResponse, error) {
	rsp, err := c.SendEmailVerificationCode(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendEmailVerificationCodeResponse(rsp)
}

// SendPasswordResetCodeWithBodyWithResponse request with arbitrary body returning *SendPasswordResetCodeResponse
func (c *ClientWithResponses) SendPasswordResetCodeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendPasswordResetCodeResponse, error) {
	rsp, err := c.SendPasswordResetCodeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendPasswordResetCodeResponse(rsp)
}

func (c *ClientWithResponses) SendPasswordResetCodeWithResponse(ctx context.Context, body SendPasswordResetCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*SendPasswordResetCodeResponse, error) {
	rsp, err := c.SendPasswordResetCode(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendPasswordResetCodeResponse(rsp)
}

// ParseSendEmailVerificationCodeResponse parses an HTTP response from a SendEmailVerificationCodeWithResponse call
func ParseSendEmailVerificationCodeResponse(rsp *http.Response) (*SendEmailVerificationCodeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SendEmailVerificationCodeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseSendPasswordResetCodeResponse parses an HTTP response from a SendPasswordResetCodeWithResponse call
func ParseSendPasswordResetCodeResponse(rsp *http.Response) (*SendPasswordResetCodeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SendPasswordResetCodeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
