version: '3.8'
services:
  pricetra-db:
    image: postgis/postgis:14-3.4
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5435:5432'
    volumes:
      - pricetra-db:/var/lib/postgresql/data
volumes:
  pricetra-db:
    driver: local
