//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type AiPromptResponse struct {
	ID        int64 `sql:"primary_key"`
	Type      AiPromptType
	Request   *string
	Response  *string
	UserID    int64
	CreatedAt time.Time
}
