//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type AiPromptType string

const (
	AiPromptType_ProductDetails AiPromptType = "PRODUCT_DETAILS"
	AiPromptType_Receipt        AiPromptType = "RECEIPT"
	AiPromptType_Nutrition      AiPromptType = "NUTRITION"
)

func (e *AiPromptType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "PRODUCT_DETAILS":
		*e = AiPromptType_ProductDetails
	case "RECEIPT":
		*e = AiPromptType_Receipt
	case "NUTRITION":
		*e = AiPromptType_Nutrition
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for AiPromptType enum")
	}

	return nil
}

func (e AiPromptType) String() string {
	return string(e)
}
