//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type AuthState struct {
	ID            uuid.UUID `sql:"primary_key"`
	LoggedInAt    time.Time
	UserID        int64
	IPAddress     *string
	Platform      UserAuthPlatformType
	DeviceType    *AuthDeviceType
	ExpoPushToken *string
}
