//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type GroceryListItem struct {
	ID            int64 `sql:"primary_key"`
	GroceryListID int64
	UserID        int64
	ProductID     *int64
	Quantity      int32
	Unit          *string
	Category      *string
	Weight        *string
	Completed     bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
