//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type ListType string

const (
	ListType_Favorites    ListType = "FAVORITES"
	ListType_ShoppingList ListType = "SHOPPING_LIST"
	ListType_Personal     ListType = "PERSONAL"
)

func (e *ListType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "FAVORITES":
		*e = ListType_Favorites
	case "SHOPPING_LIST":
		*e = ListType_ShoppingList
	case "PERSONAL":
		*e = ListType_Personal
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for ListType enum")
	}

	return nil
}

func (e ListType) String() string {
	return string(e)
}
