//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ProductView struct {
	ID        int64 `sql:"primary_key"`
	ProductID int64
	StockID   *int64
	UserID    *int64
	Origin    *string
	Platform  AuthDeviceType
	CreatedAt time.Time
}
