//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type ProductBillingType string

const (
	ProductBillingType_Create ProductBillingType = "CREATE"
	ProductBillingType_Update ProductBillingType = "UPDATE"
	ProductBillingType_Scan   ProductBillingType = "SCAN"
)

func (e *ProductBillingType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "CREATE":
		*e = ProductBillingType_Create
	case "UPDATE":
		*e = ProductBillingType_Update
	case "SCAN":
		*e = ProductBillingType_Scan
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for ProductBillingType enum")
	}

	return nil
}

func (e ProductBillingType) String() string {
	return string(e)
}
