//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ProductNutrition struct {
	ID                     int64 `sql:"primary_key"`
	ProductID              int64
	IngredientText         *string
	IngredientList         *string
	Nutriments             *string
	ServingSize            *string
	ServingSizeValue       *float64
	ServingSizeUnit        *string
	OpenfoodfactsUpdatedAt time.Time
	Vegan                  *bool
	Vegetarian             *bool
	GlutenFree             *bool
	LactoseFree            *bool
	Halal                  *bool
	Kosher                 *bool
	CreatedAt              time.Time
	UpdatedAt              time.Time
}
