//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Product struct {
	ID          int64 `sql:"primary_key"`
	Name        string
	Image       string
	Description string
	URL         *string
	Brand       string
	Code        string
	CreatedByID *int64
	UpdatedByID *int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
