//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SearchHistory struct {
	ID         int64 `sql:"primary_key"`
	SearchTerm string
	UserID     *int64
	CreatedAt  time.Time
}
