//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Stock struct {
	ID            int64 `sql:"primary_key"`
	ProductID     int64
	StoreID       int64
	BranchID      int64
	CreatedByID   *int64
	UpdatedByID   *int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LatestPriceID *int64
}
