//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type UserRoleType string

const (
	UserRoleType_SuperAdmin  UserRoleType = "SUPER_ADMIN"
	UserRoleType_Admin       UserRoleType = "ADMIN"
	UserRoleType_Contributor UserRoleType = "CONTRIBUTOR"
	UserRoleType_Consumer    UserRoleType = "CONSUMER"
)

func (e *UserRoleType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "SUPER_ADMIN":
		*e = UserRoleType_SuperAdmin
	case "ADMIN":
		*e = UserRoleType_Admin
	case "CONTRIBUTOR":
		*e = UserRoleType_Contributor
	case "CONSUMER":
		*e = UserRoleType_Consumer
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for UserRoleType enum")
	}

	return nil
}

func (e UserRoleType) String() string {
	return string(e)
}
