// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gmodel

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type Address struct {
	ID                     int64          `json:"id" sql:"primary_key"`
	CreatedAt              time.Time      `json:"createdAt"`
	UpdatedAt              time.Time      `json:"updatedAt"`
	Latitude               float64        `json:"latitude"`
	Longitude              float64        `json:"longitude"`
	Distance               *float64       `json:"distance,omitempty" alias:"address.distance"`
	MapsLink               string         `json:"mapsLink"`
	FullAddress            string         `json:"fullAddress"`
	City                   string         `json:"city"`
	AdministrativeDivision string         `json:"administrativeDivision"`
	ZipCode                string         `json:"zipCode"`
	CountryCode            string         `json:"countryCode"`
	Country                *string        `json:"country,omitempty" alias:"country.name"`
	CreatedByID            *int64         `json:"createdById,omitempty"`
	CreatedBy              *CreatedByUser `json:"createdBy,omitempty"`
	UpdatedByID            *int64         `json:"updatedById,omitempty"`
	UpdatedBy              *UpdatedByUser `json:"updatedBy,omitempty"`
}

type AdministrativeDivision struct {
	Name   string `json:"name" alias:"administrative_division.administrative_division"`
	Cities string `json:"cities"`
}

type Auth struct {
	Token     string `json:"token"`
	User      *User  `json:"user"`
	IsNewUser *bool  `json:"isNewUser,omitempty"`
}

type Branch struct {
	ID          int64          `json:"id" sql:"primary_key"`
	Name        string         `json:"name"`
	AddressID   int64          `json:"addressId"`
	Address     *Address       `json:"address"`
	StoreID     int64          `json:"storeId"`
	Store       *Store         `json:"store,omitempty"`
	CreatedByID *int64         `json:"createdById,omitempty"`
	CreatedBy   *CreatedByUser `json:"createdBy,omitempty"`
	UpdatedByID *int64         `json:"updatedById,omitempty"`
	UpdatedBy   *UpdatedByUser `json:"updatedBy,omitempty"`
}

type Brand struct {
	Brand    string `json:"brand" alias:"product.brand"`
	Products int64  `json:"products"`
}

type Category struct {
	ID               int64   `json:"id" sql:"primary_key"`
	Name             string  `json:"name"`
	Path             string  `json:"path"`
	ExpandedPathname string  `json:"expandedPathname"`
	CategoryAlias    *string `json:"categoryAlias,omitempty"`
	Depth            *int    `json:"depth,omitempty"`
}

type Country struct {
	Code                    string                    `json:"code" sql:"primary_key"`
	Name                    string                    `json:"name"`
	AdministrativeDivisions []*AdministrativeDivision `json:"administrativeDivisions"`
	Currency                *Currency                 `json:"currency,omitempty"`
	CallingCode             *string                   `json:"callingCode,omitempty"`
	Language                *string                   `json:"language,omitempty"`
}

type CreateAccountInput struct {
	Email       string  `json:"email" validate:"required,email"`
	PhoneNumber *string `json:"phoneNumber,omitempty" validate:"omitempty,e164"`
	Name        string  `json:"name" validate:"required"`
	Password    string  `json:"password" validate:"required"`
}

type CreateAddress struct {
	Latitude               float64 `json:"latitude" validate:"required,latitude"`
	Longitude              float64 `json:"longitude" validate:"required,longitude"`
	MapsLink               string  `json:"mapsLink" validate:"required,http_url"`
	FullAddress            string  `json:"fullAddress" validate:"required,contains"`
	City                   string  `json:"city" validate:"required"`
	AdministrativeDivision string  `json:"administrativeDivision" validate:"required"`
	CountryCode            string  `json:"countryCode" validate:"required,iso3166_1_alpha2"`
	ZipCode                int     `json:"zipCode" validate:"required"`
}

type CreateBranch struct {
	Name    string         `json:"name" validate:"required"`
	Address *CreateAddress `json:"address"`
	StoreID int64          `json:"storeId" validate:"required"`
}

type CreateCategory struct {
	Name       string `json:"name"`
	ParentPath []int  `json:"parentPath"`
}

type CreateProduct struct {
	Name                 string          `json:"name" validate:"required"`
	Image                *string         `json:"image,omitempty"`
	Description          string          `json:"description"`
	URL                  *string         `json:"url,omitempty" validate:"omitempty,http_url"`
	Brand                string          `json:"brand"`
	Code                 string          `json:"code" validate:"required"`
	Color                *string         `json:"color,omitempty"`
	Model                *string         `json:"model,omitempty"`
	CategoryID           int64           `json:"categoryId" validate:"required"`
	Weight               *string         `json:"weight,omitempty"`
	LowestRecordedPrice  *float64        `json:"lowestRecordedPrice,omitempty"`
	HighestRecordedPrice *float64        `json:"highestRecordedPrice,omitempty"`
	ImageFile            *graphql.Upload `json:"imageFile,omitempty"`
}

type CreateStock struct {
	ProductID int64 `json:"productId"`
	StoreID   int64 `json:"storeId"`
	BranchID  int64 `json:"branchId"`
}

type CreateStore struct {
	Name     string          `json:"name"`
	Logo     string          `json:"logo" validate:"uuid"`
	Website  string          `json:"website" validate:"http_url"`
	LogoFile *graphql.Upload `json:"logoFile,omitempty"`
}

type CreatedByUser struct {
	ID     int64   `json:"id" sql:"primary_key" alias:"created_by_user.id"`
	Name   string  `json:"name" alias:"created_by_user.name"`
	Avatar *string `json:"avatar,omitempty" alias:"created_by_user.avatar"`
	Active *bool   `json:"active,omitempty" alias:"created_by_user.active"`
}

type Currency struct {
	CurrencyCode string `json:"currencyCode" sql:"primary_key"`
	Name         string `json:"name"`
	Symbol       string `json:"symbol"`
	SymbolNative string `json:"symbolNative"`
	Decimals     int    `json:"decimals"`
	NumToBasic   *int   `json:"numToBasic,omitempty"`
}

type Mutation struct {
}

type PaginatedProductBilling struct {
	Data      []*ProductBilling `json:"data"`
	Paginator *Paginator        `json:"paginator"`
}

type PaginatedProducts struct {
	Products  []*Product `json:"products"`
	Paginator *Paginator `json:"paginator"`
}

type PaginatedUsers struct {
	Users     []*User    `json:"users"`
	Paginator *Paginator `json:"paginator"`
}

type Paginator struct {
	Next     *int `json:"next,omitempty"`
	Page     int  `json:"page"`
	Prev     *int `json:"prev,omitempty"`
	Total    int  `json:"total"`
	Limit    int  `json:"limit"`
	NumPages int  `json:"numPages"`
}

type PaginatorInput struct {
	Limit int `json:"limit" validate:"required,gt=0,lt=200"`
	Page  int `json:"page" validate:"required,gt=0"`
}

type Price struct {
	ID           int64          `json:"id" sql:"primary_key"`
	Amount       float64        `json:"amount"`
	CurrencyCode string         `json:"currencyCode"`
	ProductID    int64          `json:"productId"`
	Product      *Product       `json:"product,omitempty"`
	StoreID      int64          `json:"storeId"`
	Store        *Store         `json:"store,omitempty"`
	BranchID     int64          `json:"branchId"`
	Branch       *Branch        `json:"branch,omitempty"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
	CreatedByID  *int64         `json:"createdById,omitempty"`
	CreatedBy    *CreatedByUser `json:"createdBy,omitempty"`
	UpdatedByID  *int64         `json:"updatedById,omitempty"`
	UpdatedBy    *UpdatedByUser `json:"updatedBy,omitempty"`
}

type Product struct {
	ID                   int64          `json:"id" sql:"primary_key"`
	Name                 string         `json:"name"`
	Image                string         `json:"image"`
	Description          string         `json:"description"`
	URL                  *string        `json:"url,omitempty"`
	Brand                string         `json:"brand"`
	Code                 string         `json:"code"`
	Color                *string        `json:"color,omitempty"`
	Model                *string        `json:"model,omitempty"`
	CategoryID           int64          `json:"categoryId"`
	Category             *Category      `json:"category,omitempty"`
	Weight               *string        `json:"weight,omitempty"`
	LowestRecordedPrice  *float64       `json:"lowestRecordedPrice,omitempty"`
	HighestRecordedPrice *float64       `json:"highestRecordedPrice,omitempty"`
	CreatedAt            time.Time      `json:"createdAt"`
	UpdatedAt            time.Time      `json:"updatedAt"`
	CreatedByID          *int64         `json:"createdById,omitempty"`
	CreatedBy            *CreatedByUser `json:"createdBy,omitempty"`
	UpdatedByID          *int64         `json:"updatedById,omitempty"`
	UpdatedBy            *UpdatedByUser `json:"updatedBy,omitempty"`
}

type ProductBilling struct {
	ID              int64        `json:"id" sql:"primary_key"`
	ProductID       int64        `json:"productId"`
	Product         *Product     `json:"product,omitempty"`
	UserID          int64        `json:"userId"`
	User            *UserShallow `json:"user,omitempty"`
	CreatedAt       time.Time    `json:"createdAt"`
	Rate            float64      `json:"rate"`
	BillingRateType string       `json:"billingRateType"`
	PaidAt          *time.Time   `json:"paidAt,omitempty"`
}

type ProductSearch struct {
	Query      *string `json:"query,omitempty"`
	Category   *string `json:"category,omitempty"`
	CategoryID *int64  `json:"categoryId,omitempty"`
}

type Query struct {
}

type SaveExternalProductInput struct {
	NumPagesToQuery int     `json:"numPagesToQuery"`
	Search          string  `json:"search"`
	Category        *string `json:"category,omitempty"`
	Brand           *string `json:"brand,omitempty"`
	Upc             *string `json:"upc,omitempty"`
	Offset          *int    `json:"offset,omitempty"`
}

type SearchResult struct {
	Total  int `json:"total"`
	Added  int `json:"added"`
	Failed int `json:"failed"`
}

type Stock struct {
	ID          int64          `json:"id" sql:"primary_key"`
	ProductID   int64          `json:"productId"`
	Product     *Product       `json:"product,omitempty"`
	StoreID     int64          `json:"storeId"`
	Store       *Store         `json:"store,omitempty"`
	BranchID    int64          `json:"branchId"`
	Branch      *Branch        `json:"branch,omitempty"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
	CreatedByID *int64         `json:"createdById,omitempty"`
	CreatedBy   *CreatedByUser `json:"createdBy,omitempty"`
	UpdatedByID *int64         `json:"updatedById,omitempty"`
	UpdatedBy   *UpdatedByUser `json:"updatedBy,omitempty"`
}

type Store struct {
	ID          int64          `json:"id" sql:"primary_key"`
	Name        string         `json:"name"`
	Logo        string         `json:"logo"`
	Website     string         `json:"website"`
	CreatedByID *int64         `json:"createdById,omitempty"`
	CreatedBy   *CreatedByUser `json:"createdBy,omitempty"`
	UpdatedByID *int64         `json:"updatedById,omitempty"`
	UpdatedBy   *UpdatedByUser `json:"updatedBy,omitempty"`
}

type UpdateProduct struct {
	Name                 *string         `json:"name,omitempty"`
	Image                *string         `json:"image,omitempty"`
	Description          *string         `json:"description,omitempty"`
	URL                  *string         `json:"url,omitempty" validate:"omitempty,http_url"`
	Brand                *string         `json:"brand,omitempty"`
	Code                 *string         `json:"code,omitempty"`
	Color                *string         `json:"color,omitempty"`
	Model                *string         `json:"model,omitempty"`
	CategoryID           *int64          `json:"categoryId,omitempty"`
	Weight               *string         `json:"weight,omitempty"`
	LowestRecordedPrice  *float64        `json:"lowestRecordedPrice,omitempty"`
	HighestRecordedPrice *float64        `json:"highestRecordedPrice,omitempty"`
	ImageFile            *graphql.Upload `json:"imageFile,omitempty"`
}

type UpdateUser struct {
	Name       *string         `json:"name,omitempty"`
	Avatar     *string         `json:"avatar,omitempty" validate:"omitempty,uuid"`
	AvatarFile *graphql.Upload `json:"avatarFile,omitempty"`
	BirthDate  *time.Time      `json:"birthDate,omitempty"`
	Bio        *string         `json:"bio,omitempty"`
}

type UpdateUserFull struct {
	Email       *string         `json:"email,omitempty" validate:"omitempty,email"`
	PhoneNumber *string         `json:"phoneNumber,omitempty" validate:"omitempty,e164"`
	Name        *string         `json:"name,omitempty"`
	Avatar      *string         `json:"avatar,omitempty" validate:"omitempty,uuid"`
	AvatarFile  *graphql.Upload `json:"avatarFile,omitempty"`
	BirthDate   *time.Time      `json:"birthDate,omitempty"`
	Bio         *string         `json:"bio,omitempty"`
	Active      *bool           `json:"active,omitempty"`
	Role        *UserRole       `json:"role,omitempty"`
}

type UpdatedByUser struct {
	ID     int64   `json:"id" sql:"primary_key" alias:"updated_by_user.id"`
	Name   string  `json:"name" alias:"updated_by_user.name"`
	Avatar *string `json:"avatar,omitempty" alias:"updated_by_user.avatar"`
	Active *bool   `json:"active,omitempty" alias:"updated_by_user.active"`
}

type User struct {
	ID           int64             `json:"id" sql:"primary_key"`
	CreatedAt    time.Time         `json:"createdAt"`
	UpdatedAt    time.Time         `json:"updatedAt"`
	Email        string            `json:"email"`
	PhoneNumber  *string           `json:"phoneNumber,omitempty"`
	Name         string            `json:"name"`
	Avatar       *string           `json:"avatar,omitempty"`
	BirthDate    *time.Time        `json:"birthDate,omitempty"`
	Bio          *string           `json:"bio,omitempty"`
	Active       bool              `json:"active"`
	AuthPlatform *AuthPlatformType `json:"authPlatform,omitempty" alias:"auth_state.platform"`
	AuthDevice   *AuthDeviceType   `json:"authDevice,omitempty" alias:"auth_state.device_type"`
	AuthStateID  *int64            `json:"authStateId,omitempty" alias:"auth_state.id"`
	Role         UserRole          `json:"role"`
}

type UserFilter struct {
	Name  *string   `json:"name,omitempty"`
	Email *string   `json:"email,omitempty"`
	ID    *int64    `json:"id,omitempty"`
	Role  *UserRole `json:"role,omitempty"`
}

type UserShallow struct {
	ID     int64   `json:"id" sql:"primary_key" alias:"user.id"`
	Name   string  `json:"name" alias:"user.name"`
	Avatar *string `json:"avatar,omitempty" alias:"user.avatar"`
	Active *bool   `json:"active,omitempty" alias:"user.active"`
}

type AuthDeviceType string

const (
	AuthDeviceTypeIos     AuthDeviceType = "ios"
	AuthDeviceTypeAndroid AuthDeviceType = "android"
	AuthDeviceTypeWeb     AuthDeviceType = "web"
	AuthDeviceTypeOther   AuthDeviceType = "other"
	AuthDeviceTypeUnknown AuthDeviceType = "unknown"
)

var AllAuthDeviceType = []AuthDeviceType{
	AuthDeviceTypeIos,
	AuthDeviceTypeAndroid,
	AuthDeviceTypeWeb,
	AuthDeviceTypeOther,
	AuthDeviceTypeUnknown,
}

func (e AuthDeviceType) IsValid() bool {
	switch e {
	case AuthDeviceTypeIos, AuthDeviceTypeAndroid, AuthDeviceTypeWeb, AuthDeviceTypeOther, AuthDeviceTypeUnknown:
		return true
	}
	return false
}

func (e AuthDeviceType) String() string {
	return string(e)
}

func (e *AuthDeviceType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuthDeviceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuthDeviceType", str)
	}
	return nil
}

func (e AuthDeviceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type AuthPlatformType string

const (
	AuthPlatformTypeInternal AuthPlatformType = "INTERNAL"
	AuthPlatformTypeApple    AuthPlatformType = "APPLE"
	AuthPlatformTypeGoogle   AuthPlatformType = "GOOGLE"
)

var AllAuthPlatformType = []AuthPlatformType{
	AuthPlatformTypeInternal,
	AuthPlatformTypeApple,
	AuthPlatformTypeGoogle,
}

func (e AuthPlatformType) IsValid() bool {
	switch e {
	case AuthPlatformTypeInternal, AuthPlatformTypeApple, AuthPlatformTypeGoogle:
		return true
	}
	return false
}

func (e AuthPlatformType) String() string {
	return string(e)
}

func (e *AuthPlatformType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuthPlatformType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuthPlatformType", str)
	}
	return nil
}

func (e AuthPlatformType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type UserRole string

const (
	UserRoleSuperAdmin  UserRole = "SUPER_ADMIN"
	UserRoleAdmin       UserRole = "ADMIN"
	UserRoleContributor UserRole = "CONTRIBUTOR"
	UserRoleConsumer    UserRole = "CONSUMER"
)

var AllUserRole = []UserRole{
	UserRoleSuperAdmin,
	UserRoleAdmin,
	UserRoleContributor,
	UserRoleConsumer,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleSuperAdmin, UserRoleAdmin, UserRoleContributor, UserRoleConsumer:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
