INSERT INTO public.country VALUES ('AQ', 'Antarctica', NULL, NULL, NULL);
INSERT INTO public.country VALUES ('AN', 'Netherlands Antilles', NULL, NULL, NULL);
INSERT INTO public.country VALUES ('XK', 'Kosovo', NULL, NULL, NULL);
INSERT INTO public.country VALUES ('AD', 'Andorra', 'EUR', '+376', 'cat');
INSERT INTO public.country VALUES ('AE', 'United Arab Emirates', 'AED', '+971', 'ara');
INSERT INTO public.country VALUES ('AF', 'Afghanistan', 'AFN', '+93', 'pus');
INSERT INTO public.country VALUES ('AG', 'Antigua And Barbuda', 'XCD', '+1 268', 'eng');
INSERT INTO public.country VALUES ('AI', 'Anguilla', 'XCD', '+1 264', 'eng');
INSERT INTO public.country VALUES ('AL', 'Albania', 'ALL', '+355', 'alb');
INSERT INTO public.country VALUES ('AM', 'Armenia', 'AMD', '+374', 'arm');
INSERT INTO public.country VALUES ('AO', 'Angola', 'AOA', '+244', 'por');
INSERT INTO public.country VALUES ('AR', 'Argentina', 'ARS', '+54', 'spa');
INSERT INTO public.country VALUES ('AS', 'American Samoa', 'USD', '+1 684', 'eng');
INSERT INTO public.country VALUES ('AT', 'Austria', 'EUR', '+43', 'ger');
INSERT INTO public.country VALUES ('AU', 'Australia', 'AUD', '+61', 'eng');
INSERT INTO public.country VALUES ('AW', 'Aruba', 'AWG', '+297', 'dut');
INSERT INTO public.country VALUES ('AX', 'Aland Islands', 'EUR', '+358', 'swe');
INSERT INTO public.country VALUES ('AZ', 'Azerbaijan', 'AZN', '+994', 'aze');
INSERT INTO public.country VALUES ('BA', 'Bosnia And Herzegovina', 'BAM', '+387', 'bos');
INSERT INTO public.country VALUES ('BB', 'Barbados', 'BBD', '+1 246', 'eng');
INSERT INTO public.country VALUES ('BD', 'Bangladesh', 'BDT', '+880', 'ben');
INSERT INTO public.country VALUES ('BE', 'Belgium', 'EUR', '+32', 'dut');
INSERT INTO public.country VALUES ('BF', 'Burkina Faso', 'XOF', '+226', 'fre');
INSERT INTO public.country VALUES ('BG', 'Bulgaria', 'BGN', '+359', 'bul');
INSERT INTO public.country VALUES ('BH', 'Bahrain', 'BHD', '+973', 'ara');
INSERT INTO public.country VALUES ('BI', 'Burundi', 'BIF', '+257', 'fre');
INSERT INTO public.country VALUES ('BJ', 'Benin', 'XOF', '+229', 'fre');
INSERT INTO public.country VALUES ('BL', 'Saint Barthelemy', 'EUR', '+590', 'fre');
INSERT INTO public.country VALUES ('BM', 'Bermuda', 'BMD', '+1 441', 'eng');
INSERT INTO public.country VALUES ('BN', 'Brunei Darussalam', 'BND', '+673', 'may');
INSERT INTO public.country VALUES ('BO', 'Bolivia', 'BOB', '+591', 'spa');
INSERT INTO public.country VALUES ('BQ', 'Bonaire, Sint Eustatius and Saba', 'USD', '+599', 'dut');
INSERT INTO public.country VALUES ('BR', 'Brazil', 'BRL', '+55', 'por');
INSERT INTO public.country VALUES ('BS', 'Bahamas', 'BSD', '+1 242', 'eng');
INSERT INTO public.country VALUES ('BT', 'Bhutan', 'INR', '+975', 'dzo');
INSERT INTO public.country VALUES ('BV', 'Bouvet Island', 'NOK', NULL, NULL);
INSERT INTO public.country VALUES ('BW', 'Botswana', 'BWP', '+267', 'eng');
INSERT INTO public.country VALUES ('BY', 'Belarus', 'BYN', '+375', 'bel');
INSERT INTO public.country VALUES ('BZ', 'Belize', 'BZD', '+501', 'eng');
INSERT INTO public.country VALUES ('CA', 'Canada', 'CAD', '+1', 'eng');
INSERT INTO public.country VALUES ('CC', 'Cocos (Keeling) Islands', 'AUD', '+61', 'eng');
INSERT INTO public.country VALUES ('CD', 'Congo, Democratic Republic', 'CDF', '+243', 'fre');
INSERT INTO public.country VALUES ('CF', 'Central African Republic', 'XAF', '+236', 'fre');
INSERT INTO public.country VALUES ('CG', 'Congo', 'XAF', '+242', 'fre');
INSERT INTO public.country VALUES ('CH', 'Switzerland', 'CHF', '+41', 'ger');
INSERT INTO public.country VALUES ('CI', 'Cote D"Ivoire', 'XOF', '+225', 'fre');
INSERT INTO public.country VALUES ('CK', 'Cook Islands', 'NZD', '+682', 'eng');
INSERT INTO public.country VALUES ('CL', 'Chile', 'CLP', '+56', 'spa');
INSERT INTO public.country VALUES ('CM', 'Cameroon', 'XAF', '+237', 'eng');
INSERT INTO public.country VALUES ('CN', 'China', 'CNY', '+86', 'chi');
INSERT INTO public.country VALUES ('CO', 'Colombia', 'COP', '+57', 'spa');
INSERT INTO public.country VALUES ('CR', 'Costa Rica', 'CRC', '+506', 'spa');
INSERT INTO public.country VALUES ('CU', 'Cuba', 'CUP', '+53', 'spa');
INSERT INTO public.country VALUES ('CV', 'Cape Verde', 'CVE', '+238', 'por');
INSERT INTO public.country VALUES ('CX', 'Christmas Island', 'AUD', '+61', 'eng');
INSERT INTO public.country VALUES ('CY', 'Cyprus', 'EUR', '+357', 'gre');
INSERT INTO public.country VALUES ('CZ', 'Czech Republic', 'CZK', '+420', 'cze');
INSERT INTO public.country VALUES ('DE', 'Germany', 'EUR', '+49', 'ger');
INSERT INTO public.country VALUES ('DJ', 'Djibouti', 'DJF', '+253', 'ara');
INSERT INTO public.country VALUES ('DK', 'Denmark', 'DKK', '+45', 'dan');
INSERT INTO public.country VALUES ('DM', 'Dominica', 'XCD', '+1 767', 'eng');
INSERT INTO public.country VALUES ('DO', 'Dominican Republic', 'DOP', '+1 809', 'spa');
INSERT INTO public.country VALUES ('DZ', 'Algeria', 'DZD', '+213', 'ara');
INSERT INTO public.country VALUES ('EC', 'Ecuador', 'USD', '+593', 'spa');
INSERT INTO public.country VALUES ('EE', 'Estonia', 'EUR', '+372', 'est');
INSERT INTO public.country VALUES ('EG', 'Egypt', 'EGP', '+20', 'ara');
INSERT INTO public.country VALUES ('EH', 'Western Sahara', 'MAD', '+212', NULL);
INSERT INTO public.country VALUES ('ER', 'Eritrea', 'ERN', '+291', 'eng');
INSERT INTO public.country VALUES ('ES', 'Spain', 'EUR', '+34', 'spa');
INSERT INTO public.country VALUES ('ET', 'Ethiopia', 'ETB', '+251', 'amh');
INSERT INTO public.country VALUES ('FI', 'Finland', 'EUR', '+358', 'fin');
INSERT INTO public.country VALUES ('FJ', 'Fiji', 'FJD', '+679', 'eng');
INSERT INTO public.country VALUES ('FK', 'Falkland Islands (Malvinas)', 'FKP', '+500', 'eng');
INSERT INTO public.country VALUES ('FM', 'Micronesia, Federated States Of', 'USD', '+691', 'eng');
INSERT INTO public.country VALUES ('FO', 'Faroe Islands', 'DKK', '+298', 'fao');
INSERT INTO public.country VALUES ('FR', 'France', 'EUR', '+33', 'fre');
INSERT INTO public.country VALUES ('GA', 'Gabon', 'XAF', '+241', 'fre');
INSERT INTO public.country VALUES ('GB', 'United Kingdom', 'GBP', '+44', 'eng');
INSERT INTO public.country VALUES ('GD', 'Grenada', 'XCD', '+473', 'eng');
INSERT INTO public.country VALUES ('GE', 'Georgia', 'GEL', '+995', 'geo');
INSERT INTO public.country VALUES ('GF', 'French Guiana', 'EUR', '+594', 'fre');
INSERT INTO public.country VALUES ('GG', 'Guernsey', 'GBP', '+44', 'fre');
INSERT INTO public.country VALUES ('GH', 'Ghana', 'GHS', '+233', 'eng');
INSERT INTO public.country VALUES ('GI', 'Gibraltar', 'GIP', '+350', 'eng');
INSERT INTO public.country VALUES ('GL', 'Greenland', 'DKK', '+299', 'kal');
INSERT INTO public.country VALUES ('GM', 'Gambia', 'GMD', '+220', 'eng');
INSERT INTO public.country VALUES ('GN', 'Guinea', 'GNF', '+224', 'fre');
INSERT INTO public.country VALUES ('GP', 'Guadeloupe', 'EUR', '+590', 'fre');
INSERT INTO public.country VALUES ('GQ', 'Equatorial Guinea', 'XAF', '+240', 'spa');
INSERT INTO public.country VALUES ('GR', 'Greece', 'EUR', '+30', 'gre');
INSERT INTO public.country VALUES ('GS', 'South Georgia And Sandwich Isl.', 'GBP', NULL, 'eng');
INSERT INTO public.country VALUES ('GT', 'Guatemala', 'GTQ', '+502', 'spa');
INSERT INTO public.country VALUES ('GU', 'Guam', 'USD', '+1 671', 'eng');
INSERT INTO public.country VALUES ('GW', 'Guinea-Bissau', 'XOF', '+245', 'por');
INSERT INTO public.country VALUES ('GY', 'Guyana', 'GYD', '+592', 'eng');
INSERT INTO public.country VALUES ('HK', 'Hong Kong', 'HKD', '+852', 'chi');
INSERT INTO public.country VALUES ('HM', 'Heard Island & Mcdonald Islands', 'AUD', NULL, NULL);
INSERT INTO public.country VALUES ('HN', 'Honduras', 'HNL', '+504', 'spa');
INSERT INTO public.country VALUES ('HR', 'Croatia', 'HRK', '+385', 'hrv');
INSERT INTO public.country VALUES ('HT', 'Haiti', 'HTG', '+509', 'fre');
INSERT INTO public.country VALUES ('HU', 'Hungary', 'HUF', '+36', 'hun');
INSERT INTO public.country VALUES ('ID', 'Indonesia', 'IDR', '+62', 'ind');
INSERT INTO public.country VALUES ('IE', 'Ireland', 'EUR', '+353', 'eng');
INSERT INTO public.country VALUES ('IL', 'Israel', 'ILS', '+972', 'heb');
INSERT INTO public.country VALUES ('IM', 'Isle Of Man', 'GBP', '+44', 'eng');
INSERT INTO public.country VALUES ('IN', 'India', 'INR', '+91', 'hin');
INSERT INTO public.country VALUES ('IO', 'British Indian Ocean Territory', 'USD', '+246', 'eng');
INSERT INTO public.country VALUES ('IQ', 'Iraq', 'IQD', '+964', 'ara');
INSERT INTO public.country VALUES ('IR', 'Iran, Islamic Republic Of', 'IRR', '+98', 'per');
INSERT INTO public.country VALUES ('IS', 'Iceland', 'ISK', '+354', 'ice');
INSERT INTO public.country VALUES ('IT', 'Italy', 'EUR', '+39', 'ita');
INSERT INTO public.country VALUES ('JE', 'Jersey', 'GBP', '+44', 'eng');
INSERT INTO public.country VALUES ('JM', 'Jamaica', 'JMD', '+1 876', 'eng');
INSERT INTO public.country VALUES ('JO', 'Jordan', 'JOD', '+962', 'ara');
INSERT INTO public.country VALUES ('JP', 'Japan', 'JPY', '+81', 'jpn');
INSERT INTO public.country VALUES ('KE', 'Kenya', 'KES', '+254', 'eng');
INSERT INTO public.country VALUES ('KG', 'Kyrgyzstan', 'KGS', '+996', 'rus');
INSERT INTO public.country VALUES ('KH', 'Cambodia', 'KHR', '+855', 'khm');
INSERT INTO public.country VALUES ('KI', 'Kiribati', 'AUD', '+686', 'eng');
INSERT INTO public.country VALUES ('KM', 'Comoros', 'KMF', '+269', 'ara');
INSERT INTO public.country VALUES ('KN', 'Saint Kitts And Nevis', 'XCD', '+1 869', 'eng');
INSERT INTO public.country VALUES ('KP', 'North Korea', 'KPW', '+850', 'kor');
INSERT INTO public.country VALUES ('KR', 'Korea', 'KRW', '+82', 'kor');
INSERT INTO public.country VALUES ('KW', 'Kuwait', 'KWD', '+965', 'ara');
INSERT INTO public.country VALUES ('KY', 'Cayman Islands', 'KYD', '+1 345', 'eng');
INSERT INTO public.country VALUES ('KZ', 'Kazakhstan', 'KZT', '+7', 'kaz');
INSERT INTO public.country VALUES ('LA', 'Lao People"s Democratic Republic', 'LAK', '+856', 'lao');
INSERT INTO public.country VALUES ('LB', 'Lebanon', 'LBP', '+961', 'ara');
INSERT INTO public.country VALUES ('LC', 'Saint Lucia', 'XCD', '+1 758', 'eng');
INSERT INTO public.country VALUES ('LI', 'Liechtenstein', 'CHF', '+423', 'ger');
INSERT INTO public.country VALUES ('LK', 'Sri Lanka', 'LKR', '+94', 'sin');
INSERT INTO public.country VALUES ('LR', 'Liberia', 'LRD', '+231', 'eng');
INSERT INTO public.country VALUES ('LS', 'Lesotho', 'LSL', '+266', 'eng');
INSERT INTO public.country VALUES ('LT', 'Lithuania', 'EUR', '+370', 'lit');
INSERT INTO public.country VALUES ('LU', 'Luxembourg', 'EUR', '+352', 'fre');
INSERT INTO public.country VALUES ('LV', 'Latvia', 'EUR', '+371', 'lav');
INSERT INTO public.country VALUES ('LY', 'Libyan Arab Jamahiriya', 'LYD', '+218', 'ara');
INSERT INTO public.country VALUES ('MA', 'Morocco', 'MAD', '+212', 'ara');
INSERT INTO public.country VALUES ('MC', 'Monaco', 'EUR', '+377', 'fre');
INSERT INTO public.country VALUES ('MD', 'Moldova', 'MDL', '+373', 'rum');
INSERT INTO public.country VALUES ('ME', 'Montenegro', 'EUR', '+382', 'mot');
INSERT INTO public.country VALUES ('MF', 'Saint Martin', 'EUR', '+590', 'fre');
INSERT INTO public.country VALUES ('MG', 'Madagascar', 'MGA', '+261', 'fre');
INSERT INTO public.country VALUES ('MH', 'Marshall Islands', 'USD', '+692', 'eng');
INSERT INTO public.country VALUES ('MK', 'Macedonia', 'MKD', '+389', 'mac');
INSERT INTO public.country VALUES ('ML', 'Mali', 'XOF', '+223', 'fre');
INSERT INTO public.country VALUES ('MM', 'Myanmar', 'MMK', '+95', 'bur');
INSERT INTO public.country VALUES ('MN', 'Mongolia', 'MNT', '+976', 'mon');
INSERT INTO public.country VALUES ('MO', 'Macao', 'MOP', '+853', 'chi');
INSERT INTO public.country VALUES ('MP', 'Northern Mariana Islands', 'USD', '+1 670', 'eng');
INSERT INTO public.country VALUES ('MQ', 'Martinique', 'EUR', '+596', NULL);
INSERT INTO public.country VALUES ('MR', 'Mauritania', 'MRU', '+222', 'ara');
INSERT INTO public.country VALUES ('MS', 'Montserrat', 'XCD', '+1 664', NULL);
INSERT INTO public.country VALUES ('MT', 'Malta', 'EUR', '+356', 'mlt');
INSERT INTO public.country VALUES ('MU', 'Mauritius', 'MUR', '+230', 'eng');
INSERT INTO public.country VALUES ('MV', 'Maldives', 'MVR', '+960', 'div');
INSERT INTO public.country VALUES ('MW', 'Malawi', 'MWK', '+265', 'eng');
INSERT INTO public.country VALUES ('MX', 'Mexico', 'MXN', '+52', 'spa');
INSERT INTO public.country VALUES ('MY', 'Malaysia', 'MYR', '+60', 'msa');
INSERT INTO public.country VALUES ('MZ', 'Mozambique', 'MZN', '+258', 'por');
INSERT INTO public.country VALUES ('NA', 'Namibia', 'NAD', '+264', 'eng');
INSERT INTO public.country VALUES ('NC', 'New Caledonia', 'XPF', '+687', 'fre');
INSERT INTO public.country VALUES ('NE', 'Niger', 'XOF', '+227', 'fre');
INSERT INTO public.country VALUES ('NF', 'Norfolk Island', 'AUD', '+672', 'eng');
INSERT INTO public.country VALUES ('NG', 'Nigeria', 'NGN', '+234', 'eng');
INSERT INTO public.country VALUES ('NI', 'Nicaragua', 'NIO', '+505', 'spa');
INSERT INTO public.country VALUES ('NL', 'Netherlands', 'EUR', '+31', 'dut');
INSERT INTO public.country VALUES ('NO', 'Norway', 'NOK', '+47', 'nor');
INSERT INTO public.country VALUES ('NP', 'Nepal', 'NPR', '+977', 'nep');
INSERT INTO public.country VALUES ('NR', 'Nauru', 'AUD', '+674', 'eng');
INSERT INTO public.country VALUES ('NU', 'Niue', 'NZD', '+683', 'eng');
INSERT INTO public.country VALUES ('NZ', 'New Zealand', 'NZD', '+64', 'eng');
INSERT INTO public.country VALUES ('OM', 'Oman', 'OMR', '+968', 'ara');
INSERT INTO public.country VALUES ('PA', 'Panama', 'PAB', '+507', 'spa');
INSERT INTO public.country VALUES ('PE', 'Peru', 'PEN', '+51', 'spa');
INSERT INTO public.country VALUES ('PF', 'French Polynesia', 'XPF', '+689', 'fre');
INSERT INTO public.country VALUES ('PG', 'Papua New Guinea', 'PGK', '+675', 'eng');
INSERT INTO public.country VALUES ('PH', 'Philippines', 'PHP', '+63', 'eng');
INSERT INTO public.country VALUES ('PK', 'Pakistan', 'PKR', '+92', 'urd');
INSERT INTO public.country VALUES ('PL', 'Poland', 'PLN', '+48', 'pol');
INSERT INTO public.country VALUES ('PM', 'Saint Pierre And Miquelon', 'EUR', '+508', 'eng');
INSERT INTO public.country VALUES ('PN', 'Pitcairn', 'NZD', '+872', 'eng');
INSERT INTO public.country VALUES ('PR', 'Puerto Rico', 'USD', '+1 787', 'spa');
INSERT INTO public.country VALUES ('PS', 'Palestinian Territory, Occupied', 'JOD', '+970', 'ara');
INSERT INTO public.country VALUES ('PT', 'Portugal', 'EUR', '+351', 'por');
INSERT INTO public.country VALUES ('PW', 'Palau', 'USD', '+680', 'eng');
INSERT INTO public.country VALUES ('PY', 'Paraguay', 'PYG', '+595', 'spa');
INSERT INTO public.country VALUES ('QA', 'Qatar', 'QAR', '+974', 'ara');
INSERT INTO public.country VALUES ('RE', 'Reunion', 'EUR', '+262', 'fre');
INSERT INTO public.country VALUES ('RO', 'Romania', 'RON', '+40', 'rum');
INSERT INTO public.country VALUES ('RS', 'Serbia', 'RSD', '+381', 'srp');
INSERT INTO public.country VALUES ('RU', 'Russian Federation', 'RUB', '+7', 'rus');
INSERT INTO public.country VALUES ('RW', 'Rwanda', 'RWF', '+250', 'eng');
INSERT INTO public.country VALUES ('SA', 'Saudi Arabia', 'SAR', '+966', 'ara');
INSERT INTO public.country VALUES ('SB', 'Solomon Islands', 'SBD', '+677', 'eng');
INSERT INTO public.country VALUES ('SC', 'Seychelles', 'SCR', '+248', 'eng');
INSERT INTO public.country VALUES ('SD', 'Sudan', 'SDG', '+249', 'ara');
INSERT INTO public.country VALUES ('SE', 'Sweden', 'SEK', '+46', 'swe');
INSERT INTO public.country VALUES ('SG', 'Singapore', 'SGD', '+65', 'eng');
INSERT INTO public.country VALUES ('SH', 'Saint Helena', 'SHP', '+290', 'eng');
INSERT INTO public.country VALUES ('SI', 'Slovenia', 'EUR', '+386', 'slv');
INSERT INTO public.country VALUES ('SJ', 'Svalbard And Jan Mayen', 'NOK', '+47', NULL);
INSERT INTO public.country VALUES ('SK', 'Slovakia', 'EUR', '+421', 'slo');
INSERT INTO public.country VALUES ('SL', 'Sierra Leone', 'SLL', '+232', 'eng');
INSERT INTO public.country VALUES ('SM', 'San Marino', 'EUR', '+378', 'ita');
INSERT INTO public.country VALUES ('SN', 'Senegal', 'XOF', '+221', 'fre');
INSERT INTO public.country VALUES ('SO', 'Somalia', 'SOS', '+252', 'som');
INSERT INTO public.country VALUES ('SR', 'Suriname', 'SRD', '+597', 'dut');
INSERT INTO public.country VALUES ('SS', 'South Sudan', 'SSP', '+211', 'eng');
INSERT INTO public.country VALUES ('ST', 'Sao Tome And Principe', 'STN', '+239', 'por');
INSERT INTO public.country VALUES ('SV', 'El Salvador', 'USD', '+503', 'spa');
INSERT INTO public.country VALUES ('SY', 'Syrian Arab Republic', 'SYP', '+963', 'ara');
INSERT INTO public.country VALUES ('SZ', 'Swaziland', 'SZL', '+268', 'eng');
INSERT INTO public.country VALUES ('TC', 'Turks And Caicos Islands', 'USD', '+1 649', 'eng');
INSERT INTO public.country VALUES ('TD', 'Chad', 'XAF', '+235', 'ara');
INSERT INTO public.country VALUES ('TF', 'French Southern Territories', 'EUR', NULL, 'fre');
INSERT INTO public.country VALUES ('TG', 'Togo', 'XOF', '+228', 'fre');
INSERT INTO public.country VALUES ('TH', 'Thailand', 'THB', '+66', 'tha');
INSERT INTO public.country VALUES ('TJ', 'Tajikistan', 'TJS', '+992', 'tgk');
INSERT INTO public.country VALUES ('TK', 'Tokelau', 'NZD', '+690', 'eng');
INSERT INTO public.country VALUES ('TL', 'Timor-Leste', 'USD', '+670', 'por');
INSERT INTO public.country VALUES ('TM', 'Turkmenistan', 'TMT', '+993', 'tuk');
INSERT INTO public.country VALUES ('TN', 'Tunisia', 'TND', '+216', 'ara');
INSERT INTO public.country VALUES ('TO', 'Tonga', 'TOP', '+676', 'eng');
INSERT INTO public.country VALUES ('TR', 'Turkey', 'TRY', '+90', 'tur');
INSERT INTO public.country VALUES ('TT', 'Trinidad And Tobago', 'TTD', '+1 868', 'eng');
INSERT INTO public.country VALUES ('TV', 'Tuvalu', 'AUD', '+688', 'eng');
INSERT INTO public.country VALUES ('TW', 'Taiwan', 'TWD', '+886', 'chi');
INSERT INTO public.country VALUES ('TZ', 'Tanzania', 'TZS', '+255', 'swa');
INSERT INTO public.country VALUES ('UA', 'Ukraine', 'UAH', '+380', 'ukr');
INSERT INTO public.country VALUES ('UG', 'Uganda', 'UGX', '+256', 'eng');
INSERT INTO public.country VALUES ('UM', 'United States Outlying Islands', 'USD', '+1', 'eng');
INSERT INTO public.country VALUES ('US', 'United States', 'USD', '+1', 'eng');
INSERT INTO public.country VALUES ('UY', 'Uruguay', 'UYU', '+598', 'spa');
INSERT INTO public.country VALUES ('UZ', 'Uzbekistan', 'UZS', '+998', 'uzb');
INSERT INTO public.country VALUES ('VA', 'Holy See (Vatican City State)', 'EUR', '+379', 'ita');
INSERT INTO public.country VALUES ('VC', 'Saint Vincent And Grenadines', 'XCD', '+1 784', 'eng');
INSERT INTO public.country VALUES ('VE', 'Venezuela', 'VEF', '+58', 'spa');
INSERT INTO public.country VALUES ('VG', 'Virgin Islands, British', 'USD', '+1 284', 'eng');
INSERT INTO public.country VALUES ('VI', 'Virgin Islands, U.S.', 'USD', '+1 340', 'eng');
INSERT INTO public.country VALUES ('VN', 'Vietnam', 'VND', '+84', 'vie');
INSERT INTO public.country VALUES ('VU', 'Vanuatu', 'VUV', '+678', 'bis');
INSERT INTO public.country VALUES ('WF', 'Wallis And Futuna', 'XPF', '+681', 'fre');
INSERT INTO public.country VALUES ('WS', 'Samoa', 'WST', '+685', 'eng');
INSERT INTO public.country VALUES ('YE', 'Yemen', 'YER', '+967', 'ara');
INSERT INTO public.country VALUES ('YT', 'Mayotte', 'EUR', '+262', 'fre');
INSERT INTO public.country VALUES ('ZA', 'South Africa', 'ZAR', '+27', 'afr');
INSERT INTO public.country VALUES ('ZM', 'Zambia', 'ZMW', '+260', 'eng');
INSERT INTO public.country VALUES ('ZW', 'Zimbabwe', 'USD', '+263', 'eng');

