INSERT INTO public.currency VALUES ('AED', 'United Arab Emirates Dirham', 'د.إ.', 'د.إ.', 2, 100);
INSERT INTO public.currency VALUES ('AFN', 'Afghan Afghani', 'Af', '؋', 2, 100);
INSERT INTO public.currency VALUES ('ALL', 'Albanian Lek', 'L', 'L', 2, 100);
INSERT INTO public.currency VALUES ('AMD', 'Armenian Dram', '֏', 'դր', 2, 100);
INSERT INTO public.currency VALUES ('ANG', 'Netherlands Antillean Guilder', 'ƒ', 'ƒ', 2, 100);
INSERT INTO public.currency VALUES ('AOA', 'Angolan Kwanza', 'Kz', 'Kz', 2, 100);
INSERT INTO public.currency VALUES ('ARS', 'Argentine Peso', 'AR$', '$', 2, 100);
INSERT INTO public.currency VALUES ('AUD', 'Australian Dollar', 'AU$', '$', 2, 100);
INSERT INTO public.currency VALUES ('AWG', 'Aruban Florin', 'ƒ', 'ƒ', 2, 100);
INSERT INTO public.currency VALUES ('AZN', 'Azerbaijani Manat', 'ман', '₼', 2, 100);
INSERT INTO public.currency VALUES ('BAM', 'Bosnia and Herzegovina Convertible Mark', 'KM', 'КМ', 2, 100);
INSERT INTO public.currency VALUES ('BBD', 'Barbadian Dollar', 'BBD$', '$', 2, 100);
INSERT INTO public.currency VALUES ('BDT', 'Bangladeshi Taka', '৳', '৳', 2, 100);
INSERT INTO public.currency VALUES ('BGN', 'Bulgarian Lev', 'лв.', 'лв.', 2, 100);
INSERT INTO public.currency VALUES ('BHD', 'Bahraini Dinar', 'BD', 'د.ب.', 3, 1000);
INSERT INTO public.currency VALUES ('BIF', 'Burundian Franc', 'FBu', 'FBu', 2, 100);
INSERT INTO public.currency VALUES ('BMD', 'Bermudian Dollar', '$', '$', 2, 100);
INSERT INTO public.currency VALUES ('BND', 'Brunei Dollar', 'B$', '$', 2, 100);
INSERT INTO public.currency VALUES ('BOB', 'Bolivian Boliviano', 'Bs.', 'Bs.', 2, 100);
INSERT INTO public.currency VALUES ('BRL', 'Brazilian Real', 'R$', 'R$', 2, 100);
INSERT INTO public.currency VALUES ('BSD', 'Bahamian Dollar', '$', '$', 2, 100);
INSERT INTO public.currency VALUES ('BTN', 'Bhutanese Ngultrum', 'Nu.', 'Nu.', 2, 100);
INSERT INTO public.currency VALUES ('BWP', 'Botswana Pula', 'P', 'P', 2, 100);
INSERT INTO public.currency VALUES ('BYN', 'Belarusian Ruble', 'Br', 'руб.', 2, 100);
INSERT INTO public.currency VALUES ('BZD', 'Belize Dollar', 'BZ$', '$', 2, 100);
INSERT INTO public.currency VALUES ('CAD', 'Canadian Dollar', 'CA$', '$', 2, 100);
INSERT INTO public.currency VALUES ('CDF', 'Congolese Franc', 'FC', '₣', 2, 100);
INSERT INTO public.currency VALUES ('CHF', 'Swiss Franc', 'Fr.', '₣', 2, 100);
INSERT INTO public.currency VALUES ('CKD', 'Cook Islands Dollar', '$', '$', 2, 100);
INSERT INTO public.currency VALUES ('CLP', 'Chilean Peso', 'CL$', '$', 0, 100);
INSERT INTO public.currency VALUES ('CNY', 'Chinese Yuan', 'CN¥', '¥元', 2, 100);
INSERT INTO public.currency VALUES ('COP', 'Colombian Peso', 'CO$', '$', 2, 100);
INSERT INTO public.currency VALUES ('CRC', 'Costa Rican Colon', '₡', '₡', 2, 100);
INSERT INTO public.currency VALUES ('CUC', 'Cuban convertible Peso', 'CUC$', '$', 2, 100);
INSERT INTO public.currency VALUES ('CUP', 'Cuban Peso', '$MN', '₱', 2, 100);
INSERT INTO public.currency VALUES ('CVE', 'Cabo Verdean Escudo', 'CV$', '$', 2, 100);
INSERT INTO public.currency VALUES ('CZK', 'Czech Koruna', 'Kč', 'Kč', 2, 100);
INSERT INTO public.currency VALUES ('DJF', 'Djiboutian Franc', 'Fdj', 'ف.ج.', 2, 100);
INSERT INTO public.currency VALUES ('DKK', 'Danish Krone', 'kr.', 'kr.', 2, 100);
INSERT INTO public.currency VALUES ('DOP', 'Dominican Peso', 'RD$', '$', 2, 100);
INSERT INTO public.currency VALUES ('DZD', 'Algerian Dinar', 'DA', 'د.ج.', 2, 100);
INSERT INTO public.currency VALUES ('EGP', 'Egyptian Pound', 'E£', 'ج.م.', 2, 100);
INSERT INTO public.currency VALUES ('EHP', 'Sahrawi Peseta', 'Ptas.', 'Ptas.', 2, 100);
INSERT INTO public.currency VALUES ('ERN', 'Eritrean Nakfa', 'Nkf', 'ناكفا', 2, 100);
INSERT INTO public.currency VALUES ('ETB', 'Ethiopian Birr', 'Br', 'ብር', 2, 100);
INSERT INTO public.currency VALUES ('EUR', 'Euro', '€', '€', 2, 100);
INSERT INTO public.currency VALUES ('FJD', 'Fijian Dollar', 'FJ$', '$', 2, 100);
INSERT INTO public.currency VALUES ('FKP', 'Falkland Islands Pound', 'FK£', '£', 2, 100);
INSERT INTO public.currency VALUES ('FOK', 'Faroese Króna', 'kr', 'kr', 2, 100);
INSERT INTO public.currency VALUES ('GBP', 'Pound Sterling', '£', '£', 2, 100);
INSERT INTO public.currency VALUES ('GEL', 'Georgian Lari', '₾', '₾', 2, 100);
INSERT INTO public.currency VALUES ('GGP', 'Guernsey Pound', '£', '£', 2, 100);
INSERT INTO public.currency VALUES ('GHS', 'Ghanaian Cedi', 'GH₵', '₵', 2, 100);
INSERT INTO public.currency VALUES ('GIP', 'Gibraltar Pound', '£', '£', 2, 100);
INSERT INTO public.currency VALUES ('GMD', 'Gambian Dalasi', 'D', 'D', 2, 100);
INSERT INTO public.currency VALUES ('GNF', 'Guinean Franc', 'FG', 'FG', 2, 100);
INSERT INTO public.currency VALUES ('GTQ', 'Guatemalan Quetzal', 'Q', '$', 2, 100);
INSERT INTO public.currency VALUES ('GYD', 'Guyanese Dollar', 'G$', '$', 2, 100);
INSERT INTO public.currency VALUES ('HKD', 'Hong Kong Dollar', 'HK$', '$', 2, 100);
INSERT INTO public.currency VALUES ('HNL', 'Honduran Lempira', 'L', 'L', 2, 100);
INSERT INTO public.currency VALUES ('HRK', 'Croatian Kuna', 'kn', 'kn', 2, 100);
INSERT INTO public.currency VALUES ('HTG', 'Haitian Gourde', 'G', 'G', 2, 100);
INSERT INTO public.currency VALUES ('HUF', 'Hungarian Forint', 'Ft', 'Ft', 2, 100);
INSERT INTO public.currency VALUES ('IDR', 'Indonesian Rupiah', 'Rp', 'Rp', 2, 100);
INSERT INTO public.currency VALUES ('ILS', 'Israeli new Shekel', '₪', '₪', 2, 100);
INSERT INTO public.currency VALUES ('IMP', 'Manx Pound', '£', '£', 2, 100);
INSERT INTO public.currency VALUES ('INR', 'Indian Rupee', 'Rs.', '₹', 2, 100);
INSERT INTO public.currency VALUES ('IQD', 'Iraqi Dinar', 'د.ع.', 'د.ع.', 3, 1000);
INSERT INTO public.currency VALUES ('IRR', 'Iranian Rial', '﷼', '﷼', 2, 100);
INSERT INTO public.currency VALUES ('ISK', 'Icelandic Krona', 'kr', 'kr', 2, 100);
INSERT INTO public.currency VALUES ('JEP', 'Jersey Pound', '£', '£', 2, 100);
INSERT INTO public.currency VALUES ('JMD', 'Jamaican Dollar', 'J$', '$', 2, 100);
INSERT INTO public.currency VALUES ('JOD', 'Jordanian Dinar', 'JD', 'د.أ.', 3, 1000);
INSERT INTO public.currency VALUES ('JPY', 'Japanese Yen', '¥', '¥', 2, 100);
INSERT INTO public.currency VALUES ('KES', 'Kenyan Shilling', 'KSh', 'KSh', 2, 100);
INSERT INTO public.currency VALUES ('KGS', 'Kyrgyzstani Som', 'с', 'с', 2, 100);
INSERT INTO public.currency VALUES ('KHR', 'Cambodian Riel', '៛', '៛', 2, 100);
INSERT INTO public.currency VALUES ('KID', 'Kiribati Dollar', '$', '$', 2, 100);
INSERT INTO public.currency VALUES ('KMF', 'Comorian Franc', 'CF', 'CF', 2, 100);
INSERT INTO public.currency VALUES ('KPW', 'North Korean Won', '₩', '₩', 2, 100);
INSERT INTO public.currency VALUES ('KRW', 'South Korean Won', '₩', '₩', 2, 100);
INSERT INTO public.currency VALUES ('KWD', 'Kuwaiti Dinar', 'KD', 'د.ك.', 3, 1000);
INSERT INTO public.currency VALUES ('KYD', 'Cayman Islands Dollar', 'CI$', '$', 2, 100);
INSERT INTO public.currency VALUES ('KZT', 'Kazakhstani Tenge', '₸', '₸', 2, 100);
INSERT INTO public.currency VALUES ('LAK', 'Lao Kip', '₭N', '₭', 2, 100);
INSERT INTO public.currency VALUES ('LBP', 'Lebanese Pound', 'LL.', 'ل.ل.', 2, 100);
INSERT INTO public.currency VALUES ('LKR', 'Sri Lankan Rupee', 'Rs.', 'රු or ரூ', 2, 100);
INSERT INTO public.currency VALUES ('LRD', 'Liberian Dollar', 'L$', '$', 2, 100);
INSERT INTO public.currency VALUES ('LSL', 'Lesotho Loti', 'L', 'L', 2, 100);
INSERT INTO public.currency VALUES ('LYD', 'Libyan Dinar', 'LD', 'ل.د.', 3, 1000);
INSERT INTO public.currency VALUES ('MAD', 'Moroccan Dirham', 'DH', 'د.م.', 2, 100);
INSERT INTO public.currency VALUES ('MDL', 'Moldovan Leu', 'L', 'L', 2, 100);
INSERT INTO public.currency VALUES ('MGA', 'Malagasy Ariary', 'Ar', 'Ar', 0, 5);
INSERT INTO public.currency VALUES ('MKD', 'Macedonian Denar', 'den', 'ден', 2, 100);
INSERT INTO public.currency VALUES ('MMK', 'Myanmar Kyat', 'Ks', 'Ks', 2, 100);
INSERT INTO public.currency VALUES ('MNT', 'Mongolian Tögrög', '₮', '₮', 2, 100);
INSERT INTO public.currency VALUES ('MOP', 'Macanese Pataca', 'MOP$', 'MOP$', 2, 100);
INSERT INTO public.currency VALUES ('MRU', 'Mauritanian Ouguiya', 'UM', 'أ.م.', 0, 5);
INSERT INTO public.currency VALUES ('MUR', 'Mauritian Rupee', 'Rs.', 'रु ', 2, 100);
INSERT INTO public.currency VALUES ('MVR', 'Maldivian Rufiyaa', 'MRf', '.ރ', 2, 100);
INSERT INTO public.currency VALUES ('MWK', 'Malawian Kwacha', 'MK', 'MK', 2, 100);
INSERT INTO public.currency VALUES ('MXN', 'Mexican Peso', 'MX$', '$', 2, 100);
INSERT INTO public.currency VALUES ('MYR', 'Malaysian Ringgit', 'RM', 'RM', 2, 100);
INSERT INTO public.currency VALUES ('MZN', 'Mozambican Metical', 'MTn', 'MT', 2, 100);
INSERT INTO public.currency VALUES ('NAD', 'Namibian Dollar', 'N$', '$', 2, 100);
INSERT INTO public.currency VALUES ('NGN', 'Nigerian Naira', '₦', '₦', 2, 100);
INSERT INTO public.currency VALUES ('NIO', 'Nicaraguan Córdoba', 'C$', 'C$', 2, 100);
INSERT INTO public.currency VALUES ('NOK', 'Norwegian Krone', 'kr', 'kr', 2, 100);
INSERT INTO public.currency VALUES ('NPR', 'Nepalese Rupee', 'Rs.', 'रू', 2, 100);
INSERT INTO public.currency VALUES ('NZD', 'New Zealand Dollar', 'NZ$', '$', 2, 100);
INSERT INTO public.currency VALUES ('OMR', 'Omani Rial', 'OR', 'ر.ع.', 3, 1000);
INSERT INTO public.currency VALUES ('PAB', 'Panamanian Balboa', 'B/.', 'B/.', 2, 100);
INSERT INTO public.currency VALUES ('PEN', 'Peruvian Sol', 'S/.', 'S/.', 2, 100);
INSERT INTO public.currency VALUES ('PGK', 'Papua New Guinean Kina', 'K', 'K', 2, 100);
INSERT INTO public.currency VALUES ('PHP', 'Philippine Peso', '₱', '₱', 2, 100);
INSERT INTO public.currency VALUES ('PKR', 'Pakistani Rupee', 'Rs.', 'Rs', 2, 100);
INSERT INTO public.currency VALUES ('PLN', 'Polish Zloty', 'zł', 'zł', 2, 100);
INSERT INTO public.currency VALUES ('PND', 'Pitcairn Islands Dollar', '$', '$', 2, 100);
INSERT INTO public.currency VALUES ('PRB', 'Transnistrian Ruble', 'р.', 'р.', 2, 100);
INSERT INTO public.currency VALUES ('PYG', 'Paraguayan Guaraní', '₲', '₲', 2, 100);
INSERT INTO public.currency VALUES ('QAR', 'Qatari Riyal', 'QR', 'ر.ق.', 2, 100);
INSERT INTO public.currency VALUES ('RON', 'Romanian Leu', 'L', 'L', 2, 100);
INSERT INTO public.currency VALUES ('RSD', 'Serbian Dinar', 'din', 'дин', 2, 100);
INSERT INTO public.currency VALUES ('RUB', 'Russian Ruble', '₽', '₽', 2, 100);
INSERT INTO public.currency VALUES ('RWF', 'Rwandan Franc', 'FRw', 'R₣', 2, 100);
INSERT INTO public.currency VALUES ('SAR', 'Saudi Riyal', 'SR', 'ر.س.', 2, 100);
INSERT INTO public.currency VALUES ('SBD', 'Solomon Islands Dollar', 'SI$', '$', 2, 100);
INSERT INTO public.currency VALUES ('SCR', 'Seychellois Rupee', 'Rs.', 'Rs', 2, 100);
INSERT INTO public.currency VALUES ('SDG', 'Sudanese Pound', '£SD', 'ج.س.', 2, 100);
INSERT INTO public.currency VALUES ('SEK', 'Swedish Krona', 'kr', 'kr', 2, 100);
INSERT INTO public.currency VALUES ('SGD', 'Singapore Dollar', 'S$', '$', 2, 100);
INSERT INTO public.currency VALUES ('SHP', 'Saint Helena Pound', '£', '£', 2, 100);
INSERT INTO public.currency VALUES ('SLL', 'Sierra Leonean Leone', 'Le', 'Le', 2, 100);
INSERT INTO public.currency VALUES ('SLS', 'Somaliland Shilling', 'Sl', 'Sl', 2, 100);
INSERT INTO public.currency VALUES ('SOS', 'Somali Shilling', 'Sh.So.', 'Ssh', 2, 100);
INSERT INTO public.currency VALUES ('SRD', 'Surinamese Dollar', 'Sr$', '$', 2, 100);
INSERT INTO public.currency VALUES ('SSP', 'South Sudanese Pound', 'SS£', 'SS£', 2, 100);
INSERT INTO public.currency VALUES ('STN', 'Sao Tome and Príncipe Dobra', 'Db', 'Db', 2, 100);
INSERT INTO public.currency VALUES ('SVC', 'Salvadoran Colón', '₡', '₡', 2, 100);
INSERT INTO public.currency VALUES ('SYP', 'Syrian Pound', 'LS', 'ل.س.', 2, 100);
INSERT INTO public.currency VALUES ('SZL', 'Swazi Lilangeni', 'L', 'L', 2, 100);
INSERT INTO public.currency VALUES ('THB', 'Thai Baht', '฿', '฿', 2, 100);
INSERT INTO public.currency VALUES ('TJS', 'Tajikistani Somoni', 'SM', 'SM', 2, 100);
INSERT INTO public.currency VALUES ('TMT', 'Turkmenistan Manat', 'm.', 'T', 2, 100);
INSERT INTO public.currency VALUES ('TND', 'Tunisian Dinar', 'DT', 'د.ت.', 3, 1000);
INSERT INTO public.currency VALUES ('TOP', 'Tongan Paʻanga', 'T$', 'PT', 2, 100);
INSERT INTO public.currency VALUES ('TRY', 'Turkish Lira', 'TL', '₺', 2, 100);
INSERT INTO public.currency VALUES ('TTD', 'Trinidad and Tobago Dollar', 'TT$', '$', 2, 100);
INSERT INTO public.currency VALUES ('TVD', 'Tuvaluan Dollar', '$', '$', 2, 100);
INSERT INTO public.currency VALUES ('TWD', 'New Taiwan Dollar', 'NT$', '圓', 2, 100);
INSERT INTO public.currency VALUES ('TZS', 'Tanzanian Shilling', 'TSh', 'TSh', 2, 100);
INSERT INTO public.currency VALUES ('UAH', 'Ukrainian Hryvnia', '₴', 'грн', 2, 100);
INSERT INTO public.currency VALUES ('UGX', 'Ugandan Shilling', 'USh', 'Sh', 2, 100);
INSERT INTO public.currency VALUES ('USD', 'United States Dollar', '$', '$', 2, 100);
INSERT INTO public.currency VALUES ('UYU', 'Uruguayan Peso', '$U', '$', 2, 100);
INSERT INTO public.currency VALUES ('UZS', 'Uzbekistani Som', 'сум', 'сум', 2, 100);
INSERT INTO public.currency VALUES ('VED', 'Venezuelan bolívar digital', 'Bs.', 'Bs.', 2, 100);
INSERT INTO public.currency VALUES ('VEF', 'Venezuelan Bolívar Soberano', 'Bs.F', 'Bs.F', 2, 100);
INSERT INTO public.currency VALUES ('VND', 'Vietnamese Dong', '₫', '₫', 2, 10);
INSERT INTO public.currency VALUES ('VUV', 'Vanuatu Vatu', 'VT', 'VT', 0, NULL);
INSERT INTO public.currency VALUES ('WST', 'Samoan Tala', 'T', 'ST', 2, 100);
INSERT INTO public.currency VALUES ('XAF', 'Central African CFA Franc BEAC', 'Fr', 'Fr.', 2, 100);
INSERT INTO public.currency VALUES ('XCD', 'East Caribbean Dollar', '$', '$', 2, 100);
INSERT INTO public.currency VALUES ('XOF', 'West African CFA Franc BCEAO', '₣', '₣', 2, 100);
INSERT INTO public.currency VALUES ('XPF', 'CFP Franc (Franc Pacifique)', '₣', '₣', 0, 100);
INSERT INTO public.currency VALUES ('YER', 'Yemeni Rial', 'YR', 'ر.ي.', 2, 100);
INSERT INTO public.currency VALUES ('ZAR', 'South African Rand', 'R', 'R', 2, 100);
INSERT INTO public.currency VALUES ('ZMW', 'Zambian Kwacha', 'ZK', 'ZK', 2, 100);
INSERT INTO public.currency VALUES ('ZWB', 'RTGS Dollar', '', '', 0, NULL);
INSERT INTO public.currency VALUES ('ZWL', 'Zimbabwean Dollar', 'Z$', '$', 2, 100);

