//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Company = newCompanyTable("public", "company", "")

type companyTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnInteger
	Name        postgres.ColumnString
	Logo        postgres.ColumnString
	Website     postgres.ColumnString
	CreatedByID postgres.ColumnInteger
	UpdatedByID postgres.ColumnInteger
	CreatedAt   postgres.ColumnTimestampz
	UpdatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type CompanyTable struct {
	companyTable

	EXCLUDED companyTable
}

// AS creates new CompanyTable with assigned alias
func (a CompanyTable) AS(alias string) *CompanyTable {
	return newCompanyTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CompanyTable with assigned schema name
func (a CompanyTable) FromSchema(schemaName string) *CompanyTable {
	return newCompanyTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CompanyTable with assigned table prefix
func (a CompanyTable) WithPrefix(prefix string) *CompanyTable {
	return newCompanyTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CompanyTable with assigned table suffix
func (a CompanyTable) WithSuffix(suffix string) *CompanyTable {
	return newCompanyTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCompanyTable(schemaName, tableName, alias string) *CompanyTable {
	return &CompanyTable{
		companyTable: newCompanyTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newCompanyTableImpl("", "excluded", ""),
	}
}

func newCompanyTableImpl(schemaName, tableName, alias string) companyTable {
	var (
		IDColumn          = postgres.IntegerColumn("id")
		NameColumn        = postgres.StringColumn("name")
		LogoColumn        = postgres.StringColumn("logo")
		WebsiteColumn     = postgres.StringColumn("website")
		CreatedByIDColumn = postgres.IntegerColumn("created_by_id")
		UpdatedByIDColumn = postgres.IntegerColumn("updated_by_id")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampzColumn("updated_at")
		allColumns        = postgres.ColumnList{IDColumn, NameColumn, LogoColumn, WebsiteColumn, CreatedByIDColumn, UpdatedByIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = postgres.ColumnList{NameColumn, LogoColumn, WebsiteColumn, CreatedByIDColumn, UpdatedByIDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return companyTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		Logo:        LogoColumn,
		Website:     WebsiteColumn,
		CreatedByID: CreatedByIDColumn,
		UpdatedByID: UpdatedByIDColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
