//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ProductList = newProductListTable("public", "product_list", "")

type productListTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	UserID    postgres.ColumnInteger
	ListID    postgres.ColumnInteger
	ProductID postgres.ColumnInteger
	CreatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ProductListTable struct {
	productListTable

	EXCLUDED productListTable
}

// AS creates new ProductListTable with assigned alias
func (a ProductListTable) AS(alias string) *ProductListTable {
	return newProductListTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ProductListTable with assigned schema name
func (a ProductListTable) FromSchema(schemaName string) *ProductListTable {
	return newProductListTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ProductListTable with assigned table prefix
func (a ProductListTable) WithPrefix(prefix string) *ProductListTable {
	return newProductListTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ProductListTable with assigned table suffix
func (a ProductListTable) WithSuffix(suffix string) *ProductListTable {
	return newProductListTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newProductListTable(schemaName, tableName, alias string) *ProductListTable {
	return &ProductListTable{
		productListTable: newProductListTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newProductListTableImpl("", "excluded", ""),
	}
}

func newProductListTableImpl(schemaName, tableName, alias string) productListTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		UserIDColumn    = postgres.IntegerColumn("user_id")
		ListIDColumn    = postgres.IntegerColumn("list_id")
		ProductIDColumn = postgres.IntegerColumn("product_id")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		allColumns      = postgres.ColumnList{IDColumn, UserIDColumn, ListIDColumn, ProductIDColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{UserIDColumn, ListIDColumn, ProductIDColumn, CreatedAtColumn}
	)

	return productListTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		UserID:    UserIDColumn,
		ListID:    ListIDColumn,
		ProductID: ProductIDColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
