package gresolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"

	"github.com/pricetra/api/graph/gmodel"
)

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input gmodel.CreateCategory) (*gmodel.Category, error) {
	category, err := r.Service.CreateCategory(ctx, input)
	if err != nil {
		return nil, err
	}
	return &category, nil
}

// GetCategories is the resolver for the getCategories field.
func (r *queryResolver) GetCategories(ctx context.Context, depth *int) ([]*gmodel.Category, error) {
	categories, err := r.Service.FindCategories(ctx, depth)
	if err != nil {
		return nil, err
	}

	results := make([]*gmodel.Category, len(categories))
	for i := range categories {
		results[i] = &categories[i]
	}
	return results, nil
}
