package gresolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"fmt"

	"github.com/pricetra/api/graph/gmodel"
)

// AddGroceryListItem is the resolver for the addGroceryListItem field.
func (r *mutationResolver) AddGroceryListItem(ctx context.Context, input gmodel.CreateGroceryListItemInput, groceryListID *int64) (*gmodel.GroceryListItem, error) {
	panic(fmt.Errorf("not implemented: AddGroceryListItem - addGroceryListItem"))
}

// UpdateGroceryListItem is the resolver for the updateGroceryListItem field.
func (r *mutationResolver) UpdateGroceryListItem(ctx context.Context, groceryListItemID int64, input gmodel.CreateGroceryListItemInput) (*gmodel.GroceryListItem, error) {
	panic(fmt.Errorf("not implemented: UpdateGroceryListItem - updateGroceryListItem"))
}

// MarkGroceryListItem is the resolver for the markGroceryListItem field.
func (r *mutationResolver) MarkGroceryListItem(ctx context.Context, groceryListItemID int64, completed bool) (*gmodel.GroceryListItem, error) {
	panic(fmt.Errorf("not implemented: MarkGroceryListItem - markGroceryListItem"))
}

// GroceryLists is the resolver for the groceryLists field.
func (r *queryResolver) GroceryLists(ctx context.Context) ([]*gmodel.GroceryList, error) {
	panic(fmt.Errorf("not implemented: GroceryLists - groceryLists"))
}

// GroceryList is the resolver for the groceryList field.
func (r *queryResolver) GroceryList(ctx context.Context, groceryListID int64) (*gmodel.GroceryList, error) {
	panic(fmt.Errorf("not implemented: GroceryList - groceryList"))
}

// GroceryListItems is the resolver for the groceryListItems field.
func (r *queryResolver) GroceryListItems(ctx context.Context, groceryListID int64) ([]*gmodel.GroceryListItem, error) {
	panic(fmt.Errorf("not implemented: GroceryListItems - groceryListItems"))
}

// DefaultGroceryListItems is the resolver for the defaultGroceryListItems field.
func (r *queryResolver) DefaultGroceryListItems(ctx context.Context) ([]*gmodel.GroceryListItem, error) {
	panic(fmt.Errorf("not implemented: DefaultGroceryListItems - defaultGroceryListItems"))
}
