package gresolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"

	"github.com/pricetra/api/graph/gmodel"
)

// MySearchHistory is the resolver for the mySearchHistory field.
func (r *queryResolver) MySearchHistory(ctx context.Context, paginator gmodel.PaginatorInput) (*gmodel.PaginatedSearch, error) {
	user := r.Service.GetAuthUserFromContext(ctx)
	res, err := r.Service.PaginatedSearchHistory(ctx, user, paginator)
	if err != nil {
		return nil, err
	}
	return &res, nil
}
