package gresolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"fmt"

	"github.com/pricetra/api/graph/gmodel"
)

// MySearchHistory is the resolver for the mySearchHistory field.
func (r *queryResolver) MySearchHistory(ctx context.Context) ([]*gmodel.SearchHistory, error) {
	panic(fmt.Errorf("not implemented: MySearchHistory - mySearchHistory"))
}
