package gresolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"

	"github.com/pricetra/api/graph/gmodel"
)

// GetProductStocks is the resolver for the getProductStocks field.
func (r *queryResolver) GetProductStocks(ctx context.Context, productID int64, location *gmodel.LocationInput) ([]*gmodel.Stock, error) {
	stocks, err := r.Service.GetStocksForProduct(ctx, productID, location)
	if err != nil {
		return nil, err
	}
	res := make([]*gmodel.Stock, len(stocks))
	for i := range stocks {
		res[i] = &stocks[i]
	}
	return res, nil
}
