//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var AiPromptType = &struct {
	ProductDetails postgres.StringExpression
	Receipt        postgres.StringExpression
	Nutrition      postgres.StringExpression
}{
	ProductDetails: postgres.NewEnumValue("PRODUCT_DETAILS"),
	Receipt:        postgres.NewEnumValue("RECEIPT"),
	Nutrition:      postgres.NewEnumValue("NUTRITION"),
}
