//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var ListType = &struct {
	Favorites postgres.StringExpression
	WatchList postgres.StringExpression
	Personal  postgres.StringExpression
}{
	Favorites: postgres.NewEnumValue("FAVORITES"),
	WatchList: postgres.NewEnumValue("WATCH_LIST"),
	Personal:  postgres.NewEnumValue("PERSONAL"),
}
