//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var ProductSourceType = &struct {
	Pricetra  postgres.StringExpression
	Upcitemdb postgres.StringExpression
	Other     postgres.StringExpression
	Unknown   postgres.StringExpression
}{
	Pricetra:  postgres.NewEnumValue("Pricetra"),
	Upcitemdb: postgres.NewEnumValue("UPCitemdb"),
	Other:     postgres.NewEnumValue("Other"),
	Unknown:   postgres.NewEnumValue("Unknown"),
}
