//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var UserRoleType = &struct {
	SuperAdmin  postgres.StringExpression
	Admin       postgres.StringExpression
	Contributor postgres.StringExpression
	Consumer    postgres.StringExpression
}{
	SuperAdmin:  postgres.NewEnumValue("SUPER_ADMIN"),
	Admin:       postgres.NewEnumValue("ADMIN"),
	Contributor: postgres.NewEnumValue("CONTRIBUTOR"),
	Consumer:    postgres.NewEnumValue("CONSUMER"),
}
